course-demos: Use new design system components (#782)
Part of #749

Exception: LinkOrButton, because I think this should probably have its own PR where we migrate everything onto this, likely related to #748